project_id      = "uniqscan"
project_name    = "UniqScan"
region          = "asia-south1"
zone            = "asia-south1-a"
cluster_name    = "devops-ia-cluster"
frontend_bucket = "devops-ia-frontend-bucket"
network_name    = "default"
subnet_name     = "default"